language: python

python:
  - 3.6

script:
  - SET PYTHONPATH='/home/travis/build/kg1-thub/study_pytest/'
  - pytest -v

after_success:
  - coveralls

# notifications:
#   slack:
#     secure: your_token_key
